//USER REDUCER TYPES
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_USER = 'SET_USER'
export const LOADING_USER = 'LOADING_USER'
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ'

//UI REDUCER TYPES
export const SET_ERRORS = 'SET_ERRORS'
export const LOADING_UI = 'LOADING_UI'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const LOADING_DATA = 'LOADING_DATA'
export const STOP_LOADING_UI='STOP_LOADING_UI'

//DATA REDUCER TYPES
export const SET_IDEAS = 'SET_IDEAS'
export const LIKE_IDEA = 'LIKE_IDEA'
export const UNLIKE_IDEA = 'UNLIKE_IDEA'
export const SET_IDEA = 'SET_IDEA'
export const DELETE_IDEA = 'DELETE_IDEA'
export const POST_IDEA = 'POST_IDEA'
export const SUBMIT_COMMENT = ' SUBMIT_COMMENT';

